# Chi- Square Test

### determine the significant association with the 2 categorical variable from a single population 

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats

In [2]:
dataset = sns.load_dataset("tips")
dataset.head() 

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
dataset.shape

(244, 7)

##### Here, the two categorial variables are : sex and smoker

In [4]:
table = pd.crosstab( dataset["sex"] , dataset["smoker"])
table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [5]:
Observed_values = table.values
Observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [6]:
val= stats.chi2_contingency(table)
val

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [7]:
expected_value = val[3]
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [8]:
rows= len ( table.iloc[0:2,0])
cols = len( table.iloc[0,0:2])
rows, cols

(2, 2)

In [9]:
degree_of_freedom = (rows-1) * (cols-1 )
degree_of_freedom

1

In [10]:
alpha = 0.05

In [11]:
from scipy.stats import chi2

In [12]:
chi_square = sum([(o-e)**2/e for o,e in zip(Observed_values, expected_value)  ] )
chi_square

array([0.00119737, 0.00073745])

In [13]:
chi_square_statistics = chi_square[0] + chi_square[1]
chi_square_statistics

0.001934818536627623

In [14]:
critical_value = chi2.ppf(q=1-alpha, df = degree_of_freedom)
critical_value

3.841458820694124

In [16]:
if critical_value <= chi_square_statistics:
    print("Reject Ho, there is relationship between the two categorical variables")
else:
    print("Accept Ho, there is NO relationship between the two categorical variables")

Accept Ho, there is NO relationship between the two categorical variables


###### Or Directly calculate the P value

In [17]:
p_value =1-chi2.cdf(x= chi_square_statistics, df= degree_of_freedom)
p_value

0.964915107315732

In [18]:
if p_value <= alpha:
    print("Reject Ho, there is relationship between the two categorical variables")
else:
    print("Accept Ho, there is NO relationship between the two categorical variables")

Accept Ho, there is NO relationship between the two categorical variables


#### In the above dataset, the two categorical variables- sex and smoker are not related.